name: delivery_project
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  # ปรับปรุง SDK ให้มีความยืดหยุ่นมากขึ้น
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # สำหรับการจัดการแผนที่ (Flutter Map) - แทนที่ Google Maps
  flutter_map: ^6.1.0 
  latlong2: ^0.9.1
  cloudinary_public: ^0.23.1
  
  # สำหรับดึงตำแหน่ง GPS และแปลงพิกัด (ใช้ตัวนี้ตัวเดียว)
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  
  # Packages อื่นๆ
  image_picker: ^1.1.2 
  
  # State management + routing (GetX)
  get: ^4.6.6

  # iOS style icons
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  flutter_background_geolocation: ^4.18.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^3.0.0 # ปรับเป็นเวอร์ชันที่ใช้งานร่วมกับ SDK ได้ดีขึ้น

flutter:
  uses-material-design: true

  assets:
    # การประกาศ Assets ของท่านถูกต้อง
    - assets/image/
    - assets/config/