name: delivery_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase (เวอร์ชันล่าสุดที่ทำงานร่วมกันได้) ---
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7

  # --- State Management & Routing ---
  get: ^4.6.6

  # --- แผนที่และตำแหน่ง (เพิ่มทุกตัวที่จำเป็น) ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  location: ^6.0.2     # <--- สำหรับหน้า package_delivery_page
  geolocator: ^11.0.0  # <--- สำหรับหน้า edit_profile_page
  geocoding: ^2.2.0    # <--- สำหรับหน้า edit_profile_page

  # --- Utilities ---
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  cloudinary_public: ^0.23.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/config/